"""Domain error message constants."""

from __future__ import annotations

from typing import Final

ERR_UNKNOWN_PLAYER_PREFIX: Final[str] = "unknown player:"
ERR_MATCH_NOT_STARTED: Final[str] = "match is not started"
ERR_PLAYER_CANNOT_ACT: Final[str] = "player cannot act in current phase"
ERR_ROUND_LOCKED: Final[str] = "round is locked"
ERR_ALREADY_SUBMITTED: Final[str] = "player already submitted in this round"
ERR_UNSUPPORTED_ACTION_PREFIX: Final[str] = "unsupported action:"
ERR_MOVE_PAYLOAD_INVALID: Final[str] = "MOVE requires integer payload x/y"
ERR_MOVE_OUT_OF_BOUNDS: Final[str] = "MOVE target out of map bounds"
ERR_MOVE_NOT_ADJACENT: Final[str] = "MOVE target must be adjacent"
ERR_ACTION_NOT_ALLOWED_ON_TILE_SUFFIX: Final[str] = "is only allowed on safe building tiles"
ERR_TAKE_REQUIRES_EXPLORE: Final[str] = "TAKE requires prior EXPLORE at current tile"
ERR_ATTACK_TARGET_SELF: Final[str] = "ATTACK cannot target self"
ERR_ATTACK_TARGET_DEAD: Final[str] = "ATTACK target is dead"
ERR_ATTACK_TARGET_PHASE_ENDED: Final[str] = "ATTACK target already rested in current phase"
ERR_ATTACK_TARGET_NOT_SAME_TILE: Final[str] = "ATTACK target must be in same tile"
ERR_ATTACK_TARGET_NOT_DISCOVERED: Final[str] = "ATTACK target must be discovered first"
ERR_ATTACK_TARGET_ID_INVALID: Final[str] = "ATTACK payload.target_id must be non-empty string"
ERR_ATTACK_LOOT_PAYLOAD_INVALID: Final[str] = "ATTACK payload.loot must be object"
ERR_ATTACK_LOOT_TYPE_INVALID: Final[str] = "ATTACK payload.loot.type must be GET or TOSS"
ERR_ITEM_BUNDLE_INVALID: Final[str] = "payload.items must be a non-empty map"
ERR_ITEM_QTY_INVALID_PREFIX: Final[str] = "invalid item quantity for"
ERR_ITEM_UNKNOWN_PREFIX: Final[str] = "unknown item:"
ERR_ITEM_TOTAL_EXCEEDED_PREFIX: Final[str] = "single action item total cannot exceed"
ERR_CANNOT_SETTLE_EMPTY_ROUND: Final[str] = "cannot settle empty round"
ERR_NO_ACTIVE_PLAYERS: Final[str] = "no active players in current phase"
ERR_ROOM_FULL: Final[str] = "room is full"
ERR_ROOM_ALREADY_IN_GAME: Final[str] = "room already in game"
ERR_ROOM_PLAYER_EXISTS_PREFIX: Final[str] = "player already exists:"
ERR_ROOM_NOT_WAITING: Final[str] = "room is not in waiting status"
ERR_ROOM_NOT_IN_GAME: Final[str] = "room is not in game status"
ERR_ROOM_NOT_ACTIVE: Final[str] = "room is not active"
ERR_LOOT_WINDOW_NOT_OPEN: Final[str] = "loot window is not open"
ERR_LOOT_WINDOW_ONLY_WINNER_CAN_ACT: Final[str] = "only loot-window winner can choose GET/TOSS"
ERR_LOOT_WINDOW_ACTION_INVALID: Final[str] = "loot window action must be GET or TOSS"
ERR_MATCH_NOT_OVER: Final[str] = "match is not over"
ERR_ONLY_HOST_CAN_RESET: Final[str] = "only host can reset room"
