"""Config keys and defaults."""

from __future__ import annotations

from typing import Final

DEFAULT_APP_CONFIG_PATH: Final[str] = "config/app.toml"

ENV_APP_CONFIG: Final[str] = "APP_CONFIG"
ENV_AI_POLICY: Final[str] = "AI_POLICY"
ENV_OPENAI_API_KEY: Final[str] = "OPENAI_API_KEY"
ENV_OPENAI_MODEL: Final[str] = "OPENAI_MODEL"
ENV_OPENAI_BASE_URL: Final[str] = "OPENAI_BASE_URL"
ENV_LLM_DISCOVERY_TIMEOUT_MS: Final[str] = "LLM_DISCOVERY_TIMEOUT_MS"
ENV_LLM_INTENT_TIMEOUT_MS: Final[str] = "LLM_INTENT_TIMEOUT_MS"
ENV_NOTIFICATION_HISTORY_LIMIT: Final[str] = "NOTIFICATION_HISTORY_LIMIT"
ENV_LOOT_WINDOW_TIMEOUT_SEC: Final[str] = "LOOT_WINDOW_TIMEOUT_SEC"
ENV_ROUND_ACTION_TIMEOUT_SEC: Final[str] = "ROUND_ACTION_TIMEOUT_SEC"
ENV_ROOM_MAX_PLAYERS: Final[str] = "ROOM_MAX_PLAYERS"
ENV_MAX_AI_PLAYERS: Final[str] = "MAX_AI_PLAYERS"

DEFAULT_AI_POLICY: Final[str] = "rule"
DEFAULT_OPENAI_MODEL: Final[str] = "gpt-4.1-mini"
DEFAULT_LLM_DISCOVERY_TIMEOUT_MS: Final[int] = 600
DEFAULT_LLM_INTENT_TIMEOUT_MS: Final[int] = 1200
DEFAULT_NOTIFICATION_HISTORY_LIMIT: Final[int] = 100
DEFAULT_LOOT_WINDOW_TIMEOUT_SEC: Final[int] = 60
DEFAULT_ROUND_ACTION_TIMEOUT_SEC: Final[int] = 90
DEFAULT_ROOM_MAX_PLAYERS: Final[int] = 6
DEFAULT_MAX_AI_PLAYERS: Final[int] = 5
